id: P1D100E17
initial_creation_type: ocr
source_metadata:
  volumes:
    ca2209591dc846b5a68c36743d95765e:
      base_file: v076.txt
      image_group_id: I1PD95921
      title: ཐེག་པ་ཆེན་པོ་བསྡུས་པ།
      total_pages: 1774
      volume_number: 76
